### ISSUE TITLE
cmake遇错。

### ISSUE THREAD

**Issue by luckypoem** [ssrlive/s5proxy#1]
hi。

git clone https://github.com/ssrlive/s5proxy
cd s5proxy
mkdir build
cd build
cmake ..
显示：
...
CMake Error at cmake-libuv/CMakeLists.txt:184 (add_library):
  Cannot find source file:

    ../depends/libuv/include/uv.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "uv".
CMake Error: CMake can not determine linker language for target: uv

如何解决？

**Comment by luckypoem** [comment]
hi.

cd ~
git clone https://github.com/libuv/libuv
cd libuv
sh autogen.sh
./configure
make
make install
ldconfig 

然后再
cd ~/s5proxy
cd build
rm -rf *
cmake ..
还是遇到上面的错误。

**Comment by ssrlive** [comment]
cd ~/s5proxy
git submodule update --init
cmake . && make
